### ISSUE TITLE
why the denoise step goes so slowly

### ISSUE THREAD

**Issue by Fresh-Orange** [ayanc/rpcnn#1]
I used your algorithm to denoise, but found that it took about 20 seconds to denoise an image. I don't know what‘s the problem.

this is gpu info:

> 2019-08-12 02:16:50.414878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1
> 2019-08-12 02:16:50.414895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y Y
> 2019-08-12 02:16:50.414913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y Y
> 2019-08-12 02:16:50.414926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:73:00.0)
> 2019-08-12 02:16:50.414935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:a6:00.0)

**Comment by ayanc** [comment]
The run time is about 4 seconds for a 256x256 image (it will naturally take longer for bigger images). If it is taking 20 seconds for a 256x256 image on your machine, you might want to check your system configuration---make sure you have CUDNN installed, etc. and that there's nothing else using the same GPU and so on.

**Comment by ayanc** [comment]
Also note that it takes a longer time for the "first" image to "warm-up" (as tensorflow sets everything up). It should be much faster from the second image onwards.

**Comment by Fresh-Orange** [comment]
@ayanc Thank you. I do have a much larger picture (1241 * 376), so it seems reasonable.
